'use strict';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const STORE='masha.peremeny.workbook.v1';
const initial=()=>({step:0,intent:'',topic:'',observation:'',assumption:'',pressures:[],action:'',smallStep:'',when:'',minimum:'',done:''});
let state=initial();
const intents={prepare:{label:'Хочу разобраться заранее',title:'Знакомство — не список назначений',text:'Можно узнать основные понятия и оставить себе один вопрос. Не обязательно сразу заводить трекер, менять привычки или превращать тему в ежедневную работу.'},changes:{label:'Замечаю изменения',title:'Сначала описание, потом объяснение',text:'Не нужно прямо сейчас решать, «гормоны это или нет». Полезнее назвать конкретное изменение и то, как оно влияет на жизнь. Если оно беспокоит, это уже повод обсудить его со специалистом, не дожидаясь идеальных записей.'},noise:{label:'Устала от советов',title:'Не каждый совет становится твоим заданием',text:'Тебе не нужно выполнять рекомендации из каждой публикации. В этом листе можно выбрать, на какой вопрос ты хочешь получить ответ, и проверить один совет вместо попытки уследить за всеми.'}};
const topics={
 sleep:{label:'Сон и отдых',title:'Плохой сон — не оценка твоей дисциплины',text:'Сон может меняться в период перименопаузы. Отдых и привычки сна могут поддерживать самочувствие, но не являются гарантией результата.[2] По одному нарушению сна этот лист не определяет причину.',action:'Вместо «я совсем не умею отдыхать» опиши, что происходит: трудно заснуть, просыпаешься ночью или не чувствуешь отдыха утром. И как это отражается на дне.',placeholder:'Например: просыпаюсь ночью несколько раз в неделю; днём сложнее сосредоточиться.'},
 cycle:{label:'Изменения цикла',title:'Наблюдать — не ставить себе диагноз',text:'Изменения менструаций могут сопровождать переход к менопаузе.[1] Но сам по себе этот лист не объясняет, почему цикл изменился именно у тебя. Медицинская оценка учитывает твою ситуацию, а не только один признак.[3]',action:'Если есть изменения, запиши, что именно стало иначе по сравнению с твоим обычным циклом. Не нужно придумывать точные даты, если ты их не помнишь.',placeholder:'Например: промежутки между месячными стали непривычными для меня.'},
 mood:{label:'Настроение',title:'Тебе не нужно доказывать, что «достаточно тяжело»',text:'Изменения настроения и тревожность могут встречаться в этот период; существуют разные варианты поддержки.[2] Этот лист не определяет причину твоих переживаний и не заменяет помощь.',action:'Назови одну ситуацию: что произошло, что ты заметила в себе и с чем хотела бы получить поддержку. Без ярлыка «я стала невыносимой».',placeholder:'Например: после рабочего дня мне труднее переключиться; хочу больше тишины.'},
 energy:{label:'Силы и нагрузка',title:'Полезное действие должно помещаться в твою жизнь',text:'Питание, движение, отдых и забота о психическом благополучии могут поддерживать здоровье.[2] Это направления, а не требование одновременно построить идеальный режим. Не стоит считать новое самочувствие доказательством того, что ты недостаточно стараешься.',action:'Запиши одну нагрузку, которую можно уменьшить, разделить с кем-то или сделать иначе. Если усталость беспокоит, не объясняй её автоматически только образом жизни.',placeholder:'Например: вечером у меня не остаётся сил на бытовые дела.'},
 noise:{label:'Противоречивые советы',title:'Уверенный тон — ещё не основание следовать совету',text:'«Всем после определённого возраста нужно…» — слишком мало информации для личного решения. В рекомендациях по менопаузе важны обстоятельства, потребности и предпочтения конкретного человека.[3]',action:'Выбери один совет. Спроси: какую проблему он решает, откуда взялся и что подтверждает его применимость ко мне? Если ответов нет, не превращай его в автоматическую обязанность.',placeholder:'Например: после публикаций про гормоны чувствую, что должна срочно что-то купить.'}
};
const pressures=[
 {id:'routine',label:'Выстроить идеальный режим',take:'Забота не требует идеального режима.',note:'Отдых, питание и движение могут поддерживать здоровье.[2] Но из этого не следует, что ты обязана изменить всё одновременно. Можно выбрать один посильный шаг, а не оценивать себя по целому списку.'},
 {id:'tests',label:'Сдать всё «на всякий случай»',take:'У обследования должна быть понятная задача.',note:'Нужные обследования определяют с учётом ситуации.[3] Перед новым анализом полезно спросить: какой вопрос он прояснит и как результат повлияет на решение? Это не совет отказываться от назначенных обследований.'},
 {id:'supplements',label:'Купить добавки просто из-за возраста',take:'Сначала задача и безопасность, потом покупка.',note:'NHS рекомендует обсуждать растительные добавки и дополнительные средства с врачом.[2] Популярность и слово «натуральный» не заменяют такой разговор. Назначенные средства не отменяют по этому листу.'},
 {id:'blame',label:'Считать изменения своей ошибкой',take:'Изменения — не моральная оценка меня.',note:'Перименопауза и менопауза — естественная часть жизни.[1] Мысль «я сама виновата» не помогает установить причину самочувствия. Можно относиться к себе бережнее и при этом искать подходящую помощь.'},
 {id:'control',label:'Контролировать каждый сигнал тела',take:'Мне не нужен идеальный отчёт о себе.',note:'Рабочие записи могут быть короткими. Достаточно начать с того, что сейчас важно тебе. Не откладывай помощь, чтобы сначала накопить наблюдения или заполнить все поля.'}
];
const actions={
 question:{label:'Сформулировать свой вопрос',title:'Один вопрос вместо бесконечного поиска',note:'Закончить фразу «Я хочу понять…» — уже действие. Выбери один вопрос, ответ на который поможет принять решение, а не собрать ещё больше информации.',example:'Запишу один вопрос, который сейчас важнее остальных: что именно я хочу понять о своём самочувствии?',criterion:'Один вопрос записан.'},
 filter:{label:'Проверить один совет',title:'Проверка вместо импульсивного решения',note:'Выбери один совет, который давит на тебя. Запиши его обещание, источник и то, почему он может относиться именно к тебе. Для медицинского решения добавь вопрос своему специалисту.',example:'Возьму один тревожащий совет и проверю: что обещано, на чём основано и относится ли это ко мне.',criterion:'Я проверила один совет или записала, что ещё нужно уточнить.'},
 care:{label:'Упростить заботу о себе',title:'Сделать меньше — тоже конкретный шаг',note:'Иногда полезнее попросить помощи с одним делом, чем добавлять новую привычку. Выбери действие, которое зависит от тебя, и маленькую версию на день, когда сил мало.',example:'Сегодня вечером попрошу близких взять одно бытовое дело на себя.',criterion:'Я озвучила просьбу. Ответ другого человека — не оценка моего успеха.'},
 doctor:{label:'Обсудить изменения со специалистом',title:'Можно прийти с вопросом, не с готовым диагнозом',note:'Собери одну фразу: «Я заметила…, это влияет на…, хочу обсудить…». Записи могут помочь разговору, но их полнота не должна быть условием обращения за помощью.',example:'Свяжусь с клиникой, чтобы обсудить беспокоящие изменения и подходящее время консультации.',criterion:'Я связалась с клиникой или подготовила конкретный вопрос.'}
};
const refs={1:'https://www.nhs.uk/conditions/menopause/',2:'https://www.nhs.uk/conditions/menopause/things-you-can-do/',3:'https://www.nice.org.uk/guidance/ng23/chapter/Recommendations'};
function el(tag,cls,text){const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;}
function cited(n,text){n.replaceChildren();const parts=text.split(/(\[[123]\])/g);for(const part of parts){const m=part.match(/^\[([123])\]$/);if(m){const a=el('a','source-ref',part);a.href=refs[m[1]];a.target='_blank';a.rel='noopener noreferrer';n.append(a);}else n.append(document.createTextNode(part));}}
function renderPressures(){const box=$('#pressure-list');for(const p of pressures){const row=el('div','pressure-item');const label=el('label');const input=document.createElement('input');input.type='checkbox';input.name='pressure';input.value=p.id;input.setAttribute('aria-label',p.label);label.append(input,el('span','',p.label));const d=document.createElement('details');d.append(el('summary','','Почему это не обязательное требование'));const note=el('p');cited(note,p.note);d.append(note);row.append(label,d);box.append(row);}}
renderPressures();
$$('.choice').forEach(n=>n.querySelector('input').setAttribute('aria-label',n.querySelector('strong').textContent));
const fieldMap={observation:'observation',assumption:'assumption','small-step':'smallStep',when:'when',minimum:'minimum',done:'done'};
function resultRows(){return[
 ['С чем я пришла',intents[state.intent]?.label||'Пока определяюсь'],
 ['Мой фокус',topics[state.topic]?.label||'Оставляю себе время выбрать тему'],
 ['Что я замечаю',state.observation||'Пока без записей. Можно вернуться к этому позже.'],
 ['Моё предположение, не установленный факт',state.assumption||'Не тороплюсь объяснять причину.'],
 ['Что хочу напомнить себе',state.pressures.length?state.pressures.map(id=>pressures.find(p=>p.id===id)?.take).filter(Boolean).join('\n'):'Не обязательно брать на себя все советы сразу.'],
 ['Мой маленький шаг',state.smallStep||(state.action?actions[state.action].example:'Выбрать один вопрос, который сейчас важен мне. Это отправная точка, а не обязательное задание.')],
 ['Когда мне удобно',state.when||'Я пока не выбрала время.'],
 ['Если сил мало',state.minimum||'Уменьшить шаг: оставить только самое простое действие.'],
 ['Как я замечу, что шаг состоялся',state.done||(state.action?actions[state.action].criterion:'Я выбрала один вопрос или одно действие. Не обязана сразу почувствовать себя лучше.')]
 ];}
function updatePreview(){const wrap=$('#live-preview');wrap.replaceChildren();const bits=[];if(state.intent)bits.push(['Сегодня',intents[state.intent].label]);if(state.topic)bits.push(['Мой фокус',topics[state.topic].label]);if(state.observation)bits.push(['Наблюдение',state.observation]);if(state.pressures.length)bits.push(['Оставляю себе',state.pressures.map(id=>pressures.find(p=>p.id===id)?.take).join(' ')]);if(state.smallStep)bits.push(['Мой шаг',state.smallStep]);if(!bits.length)wrap.append(el('p','live-empty','Здесь будут появляться твои ответы. Можно пропускать вопросы — лист всё равно останется твоим.'));for(const [title,text] of bits){const b=el('div','live-block');b.append(el('strong','',title),el('p','',text.length>160?text.slice(0,160)+'…':text));wrap.append(b);}}
function showIntent(){const n=$('#intent-note'),d=intents[state.intent];n.hidden=!d;if(d)n.replaceChildren(el('h3','',d.title),el('p','',d.text));}
const defaultTopicHtml=$('#topic-note').innerHTML;
const defaultObservationPlaceholder=$('#observation').placeholder;
function showTopic(){const d=topics[state.topic];if(!d){$('#topic-note').innerHTML=defaultTopicHtml;$('#observation').placeholder=defaultObservationPlaceholder;return;}const n=$('#topic-note');n.replaceChildren(el('p','smallcaps','маленькая полезная разница'),el('h3','',d.title));const p=el('p');cited(p,d.text);n.append(p,el('p','lesson-action',d.action));$('#observation').placeholder=d.placeholder;}
function showAction(){const n=$('#action-note'),d=actions[state.action];n.hidden=!d;$('#use-example').hidden=!d;if(d)n.replaceChildren(el('h3','',d.title),el('p','',d.note));}
function renderResult(){const n=$('#personal-result');n.replaceChildren(el('p','smallcaps','В ритме женщины · Маша Хёрд'),el('h3','','Что важно мне сейчас'));for(const [title,text] of resultRows()){const b=el('section','result-line');b.append(el('h4','',title),el('p','',text));n.append(b);}const b=el('section','result-line');b.append(el('h4','','Вопрос, который можно взять с собой'),el('p','','«Какие причины моих изменений стоит рассмотреть и какой следующий шаг подходит моей ситуации?»'),el('small','','Если изменения беспокоят, не нужно ждать заполненного листа, чтобы обратиться за помощью. Здесь нет оценки симптомов, диагноза или медицинских назначений.'));n.append(b);}
function save(){if(!$('#remember').checked)return;try{localStorage.setItem(STORE,JSON.stringify(state));$('#save-status').textContent='Черновик сохранён только в этом браузере на этом устройстве.';}catch(e){$('#save-status').textContent='Браузер не разрешил сохранить черновик. Не закрывай страницу до сохранения PDF.';}}
function forget(){try{localStorage.removeItem(STORE);}catch(e){}$('#save-status').textContent='Без этой отметки ответы исчезнут после обновления или закрытия страницы.';$('#resume-notice').hidden=true;}
function restoreUi(){for(const [id,key] of Object.entries(fieldMap))$('#'+id).value=state[key];for(const name of ['intent','topic','action'])$$('input[name='+name+']').forEach(n=>n.checked=n.value===state[name]);$$('input[name=pressure]').forEach(n=>n.checked=state.pressures.includes(n.value));showIntent();showTopic();showAction();updatePreview();}
$('#remember').addEventListener('change',()=>{$('#remember').checked?save():forget();});
let savedDraft=null;
try{const raw=JSON.parse(localStorage.getItem(STORE));if(raw&&typeof raw==='object'&&!Array.isArray(raw)){savedDraft=initial();for(const [id,key] of Object.entries(fieldMap)){const value=raw[key];savedDraft[key]=typeof value==='string'?value.slice(0,$('#'+id).maxLength):'';}for(const [key,map] of [['intent',intents],['topic',topics],['action',actions]])savedDraft[key]=Object.prototype.hasOwnProperty.call(map,raw[key])?raw[key]:'';savedDraft.pressures=Array.isArray(raw.pressures)?pressures.filter(p=>raw.pressures.includes(p.id)).map(p=>p.id):[];savedDraft.step=Number.isInteger(raw.step)?Math.max(1,Math.min(5,raw.step)):1;$('#resume-notice').hidden=false;}}
catch(e){try{localStorage.removeItem(STORE);}catch(ignore){}}
$('#resume').addEventListener('click',()=>{if(!savedDraft)return;state=savedDraft;$('#remember').checked=true;restoreUi();showStep(state.step);});
function showStep(step){state.step=Math.max(0,Math.min(5,step));$('#welcome').hidden=state.step!==0;$('#workbook').hidden=state.step===0;$$('.page').forEach(n=>n.hidden=Number(n.dataset.step)!==state.step);$('#step-caption').textContent=state.step<5?`Шаг ${state.step} из 4`:'Твой результат';$('#progress-fill').style.width=(Math.min(state.step,4)/4*100)+'%';$('#back').textContent=state.step===1?'← На начало':'← Назад';if(state.step===5)renderResult();updatePreview();save();window.scrollTo({top:0,behavior:'instant'});if(state.step>0)$(`.page[data-step="${state.step}"] h2`).focus({preventScroll:true});}
$('#start').addEventListener('click',()=>showStep(1));$('#back').addEventListener('click',()=>showStep(state.step-1));$$('[data-next]').forEach(b=>b.addEventListener('click',()=>showStep(Number(b.dataset.next))));$('#finish').addEventListener('click',()=>showStep(5));$('#edit').addEventListener('click',()=>showStep(1));
$$('input[name=intent]').forEach(i=>i.addEventListener('change',()=>{state.intent=i.value;showIntent();updatePreview();save();}));
$$('input[name=topic]').forEach(i=>i.addEventListener('change',()=>{state.topic=i.value;showTopic();updatePreview();save();}));
$$('input[name=pressure]').forEach(i=>i.addEventListener('change',()=>{state.pressures=$$('input[name=pressure]:checked').map(n=>n.value);if(i.checked)i.closest('.pressure-item').querySelector('details').open=true;updatePreview();save();}));
$$('input[name=action]').forEach(i=>i.addEventListener('change',()=>{state.action=i.value;showAction();save();}));
Object.entries(fieldMap).forEach(([id,key])=>$('#'+id).addEventListener('input',e=>{state[key]=e.target.value;updatePreview();save();}));
$('#use-example').addEventListener('click',()=>{if(state.smallStep&&!confirm('Заменить твой текст примером?'))return;state.smallStep=actions[state.action].example;$('#small-step').value=state.smallStep;updatePreview();save();$('#small-step').focus();});
$('#reset').addEventListener('click',()=>{if(!confirm('Очистить ответы и начать заново? Скачанные PDF останутся у тебя.'))return;state=initial();savedDraft=null;forget();$$('input[type=radio],input[type=checkbox]').forEach(n=>n.checked=false);Object.keys(fieldMap).forEach(id=>$('#'+id).value='');$$('.pressure-item details').forEach(n=>n.open=false);showIntent();showTopic();showAction();showStep(0);});
updatePreview();
